### ISSUE TITLE
Gocomics module does not work

### ISSUE THREAD

**Issue by bakisfigus** [SylvainDe/ComicBookMaker#83]
When the comic landing page has a "Read *** from the Beginning" link, the script gets the "first comic" right, it downloads it but then stops with a "next/first comic will be None"

C:\*> python comicbookmaker.py --comic brevity --loglevel 10
DEBUG:root:Starting
DEBUG:root:update brevity start
DEBUG:root:_create_output_dir brevity start
DEBUG:root:_create_output_dir brevity done
DEBUG:root:_load_db_from_file brevity start
DEBUG:root:update brevity last comic is https://www.gocomics.com/brevity/2005/01/03
DEBUG:root:get_next_comic brevity starting 'get_next_comic' from https://www.gocomics.com/brevity/2005/01/03
DEBUG:root:get_content (url : https://www.gocomics.com/brevity/2005/01/03)
DEBUG:root:urlopen_wrapper (url : https://www.gocomics.com/brevity/2005/01/03)
DEBUG:root:get_next_link brevity Next link is None
DEBUG:root:get_next_comic brevity next/first comic will be None (url is https://www.gocomics.com/brevity/2005/01/03)
brevity : nothing new
DEBUG:root:update brevity done

When the comic landing page has no "Read *** from the Beginning" link, the script apparently gets the last comic's url instead of the first, doest not download anything and then stops with a "next/first comic will be None":

C:\*> python comicbookmaker.py --comic peanuts --loglevel 10
DEBUG:root:Starting
DEBUG:root:update peanuts start
DEBUG:root:_create_output_dir peanuts start
DEBUG:root:_create_output_dir peanuts done
DEBUG:root:_load_db_from_file peanuts start
DEBUG:root:update peanuts last comic is None
DEBUG:root:get_next_comic peanuts starting 'get_next_comic' from None
DEBUG:root:get_content (url : http://www.gocomics.com/peanuts)
DEBUG:root:urlopen_wrapper (url : http://www.gocomics.com/peanuts)
DEBUG:root:get_content (url : http://www.gocomics.com/peanuts/2019/03/30)
DEBUG:root:urlopen_wrapper (url : http://www.gocomics.com/peanuts/2019/03/30)
DEBUG:root:get_next_comic peanuts next/first comic will be None (url is None)
peanuts : nothing new
DEBUG:root:update peanuts done

and

C:\*> python comicbookmaker.py --comic calvin-goc --loglevel 10
DEBUG:root:Starting
DEBUG:root:update calvin-goc start
DEBUG:root:_create_output_dir calvin-goc start
DEBUG:root:_create_output_dir calvin-goc done
DEBUG:root:_load_db_from_file calvin-goc start
DEBUG:root:update calvin-goc last comic is None
DEBUG:root:get_next_comic calvin-goc starting 'get_next_comic' from None
DEBUG:root:get_content (url : http://www.gocomics.com/calvinandhobbes)
DEBUG:root:urlopen_wrapper (url : http://www.gocomics.com/calvinandhobbes)
DEBUG:root:get_content (url : http://www.gocomics.com/calvinandhobbes/2019/03/30)
DEBUG:root:urlopen_wrapper (url : http://www.gocomics.com/calvinandhobbes/2019/03/30)
DEBUG:root:get_next_comic calvin-goc next/first comic will be None (url is None)
calvin-goc : nothing new
DEBUG:root:update calvin-goc done

**Comment by bakisfigus** [comment]
I've tried several non-gocomics modules and everything works fine.

**Comment by SylvainDe** [comment]
Thanks for your feedback, I'll have a look at this!

**Comment by bakisfigus** [comment]
I include several "get_soup_at_url" logfiles

[get_soup_at_url.zip](https://github.com/SylvainDe/ComicBookMaker/files/3025588/get_soup_at_url.zip)

**Comment by SylvainDe** [comment]
Thanks! I'll have a look at this in the next days :-)

Le sam. 30 mars 2019 à 15:40, bakisfigus <notifications@github.com> a
écrit :

**Comment by SylvainDe** [comment]
Note: https://github.com/SylvainDe/ComicBookMaker/commit/cd785baf0312f35cd1653a3234b63b8f79398819 is related to this issue as well.

**Comment by SylvainDe** [comment]
From what I can see in the raw file:

`<a role='button' href='/peanuts/1950/10/02' class='fa btn btn-outline-secondary btn-circle fa fa-backward sm ' title='' ></a>`

From what I can see in the content file:


`<a class="fa btn btn-outline-secondary btn-circle fa fa-backward sm" href="/peanuts/1950/10/02" role="button" title=""></a>`

It seems like a whitespace after the "sm" disappears for some reason. I do not know if this is a pretty-printing feature of BeautifulSoup...

@bakisfigus Can you give it a try after removing the final whitespace after sm in https://github.com/SylvainDe/ComicBookMaker/blob/master/comics.py#L5171 ?

**Comment by bakisfigus** [comment]
Good news. After removing the final whitespace after sm in [https://github.com/SylvainDe/ComicBookMaker/blob/master/comics.py#L5171](url), the script correctly downloaded the first comic (tried calvin-goc and peanuts, both with no nav landing page) and then stopped. 

then I tried to remove also the final whitespaces in [ https://github.com/SylvainDe/ComicBookMaker/blob/master/comics.py#L5176](url) and [ https://github.com/SylvainDe/ComicBookMaker/blob/master/comics.py#L5176](url) and now it works like a breeze!

**Comment by SylvainDe** [comment]
Thanks @bakisfigus for the feedback.
At first I suspected that maybe the OS could have an impact on this but now that I retry on a freshly created venv on Linux, I observe the same behavior as yours.
This could be related to https://bugs.launchpad.net/beautifulsoup/+bug/1787453 .
If I get a bit of spare time, I'll try to investigate further. In the meantime, I'll submit a commit to fix this while ensuring backward compatibility.

**Comment by SylvainDe** [comment]
@bakisfigus This should now be fixed, thanks again for your feedback :)

I'll keep the issue opened to try to find more about this behavior change in BS4.

**Comment by SylvainDe** [comment]
I've opened this issue: https://bugs.launchpad.net/beautifulsoup/+bug/1824502 .

**Comment by SylvainDe** [comment]
Note: if the same kind of issue happened somewhere, it might be worth defining a Soup wrapper to handle compatibility issues like this one.

**Comment by SylvainDe** [comment]
Not directly related to this bug but here are my notes if I need to tests bs4 again in the future:

```
     sudo apt-get install bzr
     bzr branch lp:beautifulsoup
     cd beautifulsoup/

     python3.6 -m venv bsenv
     source bsenv/bin/activate

     pip install 2to3
     pip install soupsieve

     2to3 -w bs4

     python -m unittest discover -s bs4
```
